blank_issues_enabled: false
contact_links:
  contact_links:
  - name: Feature request
    url: https://github.com/laravel-turbo/jetstream-turbo/discussions/new
    about: For ideas or feature requests
  - name: Support question
    url: https://github.com/laravel-turbo/jetstream-turbo/discussions
    about: 'If you need help using the library, click:'
  - name: Documentation issue
    url: https://github.com/laravel-turbo/docs
    about: For documentation issues, open a pull request at the laravel-turbo/docs repository
